version: 2.1
jobs:
  Release:
    docker:
      - image: node:11.8.0-alpine
    steps:
      - run:
          name: Install and configuire helm
          command: sudo curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz | tar xz && sudo mv linux-amd64/helm /bin/helm && sudo rm -rf linux-amd64
      - run:
          name: Initialize helm
          command:  helm init --client-only --kubeconfig=$HOME/.kube/kubeconfig
      - run:
          name: Release
          command: |
            helm upgrade health-care-server ./

workflows:
  version: 2
  default_job:
    jobs:
      - Release
