version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.7.1
  helm: circleci/helm@1.0.0
jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcp-gke/install
      - gcp-gke/rollout-image:
          cluster: cluster-1
          container: project-for-video
          deployment: project-for-video
          namespace: project-for-video
          image: gcr.io/project-for-video/project-for-video
          tag: latest
workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                [project-for-video-dev]