jobs:
  delete-helm-release:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - helm/delete-helm-release:
          helm-version: v2
          release-name: health-care-service
          timeout: 600s
  install-helm-chart:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - helm/install-helm-chart:
          chart: /
          helm-version: v2
          release-name: health-care-service
orbs:
  aws-eks: circleci/aws-eks@0.2
  helm: circleci/helm@1.0
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: test-cluster
      - install-helm-chart:
          cluster-name: test-cluster
          requires:
            - aws-eks/create-cluster
      - delete-helm-release:
          cluster-name: test-cluster
          requires:
            - install-helm-chart
      - aws-eks/delete-cluster:
          cluster-name: test-cluster
          requires:
            - delete-helm-release
          wait: true