version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.7.1
  helm: circleci/helm@1.0.0
jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcp-gke/install
      - gcp-gke/rollout-image:
          cluster: cluster-1
          container: health-care-server
          deployment: health-care-server
          image: gcr.io/project-1-284510/health-care-server
          tag: 3464546d9baab6798cdfd1bef1d256f4b68c6bd7
      - helm/upgrade-helm-chart:
          helm-version: v3.0.0
          release-name: health-care-server
          chart: health-care-server
workflows:
  main:
    jobs:
      - deploy