version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.7.1
  helm: circleci/helm@1.0.0
jobs:
  test:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: test
          command: |
            source ./setup-env.sh
            echo "This is pipeline ID($X)($tag)xxxxxx"

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcp-gke/install
      - gcp-gke/rollout-image:
          cluster: "${CLUSTER}"
          container: "${CONTAINER}"
          deployment: "${DEPLOYMENT}"
          image: "${IMAGE}"
          tag: 3464546d9baab6798cdfd1bef1d256f4b68c6bd7
workflows:
  main:
    jobs:
      - test
      - deploy