version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build:
    description: Install npm
    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
    machine: true
    steps:
      - checkout
      # Install node
      - node/install
      # Install npmERROR: (gcloud.config.set) 
      - node/install-npm
      # Download and cache dependencies
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: health-care-server
          tag: "latest" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: health-care-server
          tag: "latest" #Change version number e.g to 'v3' when updating application
    
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcp-gke/install
      - gcp-gke/rollout-image:
          cluster: cluster-1
          container: test
          deployment: health-care-server
          image: gcr.io/project-1-284510/health-care-server
          tag: 3464546d9baab6798cdfd1bef1d256f4b68c6bd7
workflows:
  main:
    jobs:
      - deploy