version: 2.1
orbs:
  node: circleci/node@3.0.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.7.1
  helm: circleci/helm@1.0.0
jobs:
  test:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: test
          command: |
            A="$(grep X setup-env.sh | awk -F"'=' '{print $2}')"
            export P = "{$A}"
            echo "This is pipeline ID($A)($X)xxxxxx"
      - run:
          name: aa
          command: |
            echo "This is pipeline ID($P)($X)xxxxxx"

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcp-gke/install
      - gcp-gke/rollout-image:
          cluster: cluster-1
          container: health-care-server
          deployment: health-care-server
          image: gcr.io/project-1-284510/health-care-server
          tag: 3464546d9baab6798cdfd1bef1d256f4b68c6bd7
workflows:
  main:
    jobs:
      - test
      # - deploy